<a href="https://colab.research.google.com/github/thiagopereiramagalhaes/Algebra-linear-com-python/blob/main/%C3%81lgebra_linear_com_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Thiago Pereira Magalhães**
**GitHub:** [thiagopereiramagalhaes](https://github.com/thiagopereiramagalhaes)  
**Linkedin:** [thiagopmagalhaes](https://www.linkedin.com/in/thiagopmagalhaes/)  
**Portifólio:** [Portfolio](https://github.com/thiagopereiramagalhaes/Portfolio)  
**Repositório:** [Álgebra-linear-com-python](https://github.com/thiagopereiramagalhaes/Algebra-linear-com-python)  



---



# Álgebra linear com python

A álgebra linear utiliza alguns conceitos e estruturas fundamentais da matemática, vetores, espaços vetoriais, transformações lineares, sistemas de equações lineares e matrizes. Constitui um segmento de aprendizagem essencial para trabalhar com tratamento de dados e Machine Learning. Compreender álgebra linear melhora definitivamente a forma como desenvolvemos os modelos preditivos.

<img width="300px" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Linear_subspaces_with_shading.svg/1200px-Linear_subspaces_with_shading.svg.png">
<img width="400px" src="https://i2.wp.com/www.vooo.pro/insights/wp-content/uploads/2018/05/Python_logo.png?fit=1200%2C508&ssl=1">

## Iniciando com matrizes
Vamos começar entendendo o conceito de matrizes e vetores.

### Matriz
De forma simplificada, matriz é uma tabela com linhas e colunas(m x n).
Onde m representa o número de linhas e n o número de colunas. 
```
|0|1|2|3|
|0|1|2|3|
|0|1|2|3|
```

### Vetor
E os vetores? Bom, seguindo o mesmo conceito que uma matriz, podemos definir um vetor como uma lista. 
```
|0|1|2|3|
```

### Vetor de vetores
O vetor de vetores muitas vezes é confundido com matriz, mas, não é, os tamanhos de cada linha ou coluna são variáveis. Uma matriz mantém tudo do mesmo tamanho. Vamos entender melhor daqui a pouco...

### Matrizes retangulares
São matrizes que possuem a quantidade de linhas e colunas diferentes umas das outras.
*   m != n

```
|X|X|X|  
|X|X|X|  
|X|X|X|
|X|X|X|
```

### Matrizes quadradas
São as matrizes que possuem a mesma quantidade de linhas que a quantidade de colunas. 
*   m = n
  
```
|X|X|X|X|
|X|X|X|X|  
|X|X|X|X|
|X|X|X|X|
```

### Matrizes linhas
Possui uma única linha (m = 1).

```
|0|1|2|3|
```

### Matrizes colunas
Possui uma única coluna (n = 1).

```
|0|
|1| 
|2|
|3|
```

### Diagonais
As diagonais das matrizes possuem denominações próprias. Cada matriz que seja quadrada, possui duas diagonais, a diagonal principal e a diagonal secundaria. A diagonal que percorre da extremidade da esquerda para a direita é chamada de principal e da direita para esquerda é chamada de secundaria.

*   Diagonal principal

```
|1|X|X|X|
|X|2|X|X|  
|X|X|3|X|
|X|X|X|4|
```

*   Diagonal secundária

```
|X|X|X|1|
|X|X|2|X|  
|X|3|X|X|
|4|X|X|X|
```

### Matriz triangular inferior
As matrizes triangulares são matrizes quadradas, ou seja, possuem diagonais. A triangular inferior é dividida pela sua diagonal principal. Formando dois triângulos, um, na sua parte superior com todos os valores vazios e outro na parte inferior com todos os seus respectivos valores. 

```
|1|0|0|0|
|1|2|0|0|  
|1|2|3|0|
|1|2|3|4|
```
### Matriz triangular superior
A matriz triangular superior segue a mesma estrutura padronizada da inferior, com algumas pequenas diferenças. Esta, no que lhe concerne, possui a formação do triangulo vazio na parte inferior e os seus valores na parte superior.

```
|1|1|1|1|
|0|2|2|2|  
|0|0|3|3|
|0|0|0|4|
```


### Matriz diagonal
Agora vamos conhecer algumas peculiaridades das matrizes.
Conhecemos como matriz diagonal as matrizes que possuem valores apenas nos elementos que pertencem as suas diagonais. Todos os elementos restantes da matriz possuem valores vazios.

```
|1|0|0|0|
|0|2|0|0|  
|0|0|3|0|
|0|0|0|4|
```

### Matriz identidade
Seguindo com as peculiaridades, temos a matriz identidade semelhante com a matriz diagonal, esta categoria de matriz possui a sua diagonal com elementos formados por apenas valores iguais a '1'.

```
|1|0|0|0|
|0|1|0|0|  
|0|0|1|0|
|0|0|0|1|
```

### Matriz simétrica
Parecido com a estrutura das matrizes explicadas anteriormente. Neste caso, temos a divisão da matriz pela sua diagonal principal. Os dois triângulos formados na parte superior e inferior possuem os mesmos elementos e valores de forma simétrica.

```
|X|1|2|3|
|1|X|1|2|  
|2|1|X|3|
|3|2|3|X|
```

### Operações aritméticas com matrizes
É muito simples as operações com matrizes. Devemos apenas ficarmos atentos com algumas regras. Por exemplo, para soma e subtração as matrizes devem ser de mesma dimensão. Não obrigatoriamente precisam ser quadradas. Irei começar explicando as operações mais simples, a intenção é utilizar o python para tratar as matrizes. Posteriormente irei aplicar no código operações mais complexas.

### Soma
Na soma de matrizes somamos índice por índice. No final alocamos em uma nova matriz os resultados nos seus respectivos índices anteriores. Para exemplificar, vamos somar primeiramente duas listas.

```
índice A0 = 2
índice A1 = 4
índice B0 = 3
Índice B1 = 5

A0 + B0 = 5
A1 + B1 = 9
C0 = 5
C1 = 9

|2||4| + |3||5| = |5||9|
```
Bom, agora vamos somar duas matrizes. Para facilitar o seu raciocínio imagine que vamos apenas adicionar mais uma lista para cada conjunto de listas. O processo continua o mesmo, somar índice por índice e realocar em uma nova matriz nos mesmos locais que os elementos das matrizes anteriores.

```
índice A0 = 2
índice A1 = 4
índice A2 = 1
índice A3 = 3

índice B0 = 3
Índice B1 = 5
índice B2 = 2
Índice B3 = 4

A0 + B0 = 5
A1 + B1 = 9
A2 + B2 = 3
A3 + B3 = 7

C0 = 5
C1 = 9
C2 = 3
C3 = 7

|2||4|   |3||5|   |5||9|
 -  -  +  -  -  =  -  -
|1||3|   |2||4|   |3||7|
```

### Subtração
A subtração entre matrizes ocorre da mesma forma que a soma, não muda a estrutura. Vamos realizar a subtração de duas matrizes.

```
|6||2| ' |3||3| ' | 3| |-1| 
|0||4| - |5||4| = |-5| | 0|
|1||5| ' |8||2| ' |-7| | 3|
```


### Produtos entre matrizes
Temos regras específicas para soma e subtração, para produtos entre matrizes não é diferente. Vamos lá, apenas é possível o produto de duas matrizes quando temos o número de linhas de uma matriz igual ao número de colunas de outra matriz. Vale lembrar que, o produto não é comutativo, o resultado de uma matriz 'A x B'  não é o mesmo que 'B x A'. A multiplicação ocorre sempre entre linhas e colunas. Vamos exemplificar melhor posteriormente com o python.

Temos que definir mais alguns assuntos antes de partir para o python. Estamos chegando lá, prometo que falta pouco. 

### Multiplicação escalar
O termo multiplicação escalar refere-se quando temos um determinado número e precisamos multiplicar por todos os índices de uma determinada matriz.

```
5 . 6 = 30
5 . 2 = 10
5 . 0 = 0
5 . 4 = 20
5 . 1 = 5
5 . 5 = 25

    |6||2|   |30| |10|
5 . |0||4| = |0 | |20|
    |1||5|   |5 | |25|
```

### Matriz transposta
A matriz transposta pode parecer ser complicada de entender, principalmente quando aplicada diretamente com uma linguagem de programação. Devemos entender a base antes de qualquer código. É importante saber a base e os conceitos antes de manipular matrizes com o python.

Matriz transposta nada mais é que escrever as linhas de uma matriz em colunas. Da seguinte forma:

```
|0||1|   |0||2||4|
|2||3| = |1||3||5|
|4||5|
```

### Divisão
Tá! E a divisão? A divisão é algo um pouco peculiar, no entanto, existe um truque para facilitar a operação. Por ser algo desgastante vamos exemplificar melhor posteriormente. A divisão de duas matrizes é o mesmo que a multiplicação da matriz 'A' pela 'B' inversa. Aqui que entra a questão, B deve estar com as posições investidas para realizar  a multiplicação, logo, o resultado é o mesmo que a divisão. 

## Matemática com python e a biblioteca NumPy
O python facilita muito o tratamento e operações de matrizes, um ótimo aliado para resolver problemas matemáticos. Possibilitando o uso com álgebra linear. Utilizaremos a biblioteca NumPy para deixar ainda mais completo e muito mais rápido. NumPy é uma biblioteca utilizada para diversos fins matemáticos e estatísticos.  

<img width="600px" src="https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png"> 

### Vamos colocar a mão na massa!
Precisamos importar a biblioteca numpy. Logo após, nomearemos como 'np'.

In [ ]:
import numpy as np

### Estrutura
Ao longo desse material explicarei sobre o tratamento de matrizes e vetores quanto as suas estruturas. Vamos começar falando sobre suas dimensões. Toda matriz ou vetor possui uma dimensão, isso é claro.

Existem três principais dimensões, falaremos sobre cada uma delas. É importante lembrar que é raro ter mais de três dimensões, embora uma matriz possa ter até 32 dimensões.

Chegamos na parte onde devo explicar o vetor e o vetor de vetores. Bom, é verdade que um vetor pode conter uma lista de vetores, confundido muitas vezes com uma matriz. Um vetor pode ter mais de uma categoria de dados, além disso, pode ter mais de uma dimensão. A matriz no que lhe concerne possui sempre uma estrutura uniforme e um vetor pode ter o tamanho de linhas ou colunas de variados tamanhos. Uma matriz por padrão sempre terá uma estrutura bidimensional, a menos que alguém altere.

### Estruturas unidimensionais
Um array unidimensional possui obviamente apenas uma dimensão. É muito simples criar matrizes e vetores com o python. Vamos começar definindo um nome. Por motivos didáticos colocaremos seu nome de arrayUni. Após definir um nome, usaremos o numpy para criar um vetor com os nossos dados. Será uma lista com os seguintes dados"'Python', 'R', 'SQL'". Observe que usaremos apenas um par de '[ ]' entre os dados. Isso indica que utilizaremos apenas uma dimensão. 

In [ ]:
'''Comentários
Nome: arrayUni
NumPy: np
Tipo: array
Dimensão: unidimensional
dados: 'Python', 'R', 'SQL'
'''
arrayUni = np.array(['Python', 'R', 'SQL'])

# Vamos chamar esse array agora
arrayUni

array(['Python', 'R', 'SQL'], dtype='<U6')


### Estruturas bidimensionais
Seguiremos quase o mesmo que o exemplo anterior. As matrizes bidimensionais podem ter mais de uma categoria de dados. Para matrizes e vetores com duas dimensões é preciso encapsular entre parênteses. Dessa forma "[ [ 'valor', 'ano', 'id'], [25, 2021, 1421] ]". Vamos criar uma matriz e um vetor bidimensional.

In [ ]:
# Matriz bidimensional
matrixBi = np.matrix([['valor', 'ano','id'], [25, 2021, 1421]])
matrixBi

matrix([['valor', 'ano', 'id'],
        ['25', '2021', '1421']], dtype='<U5')

### Estruturas tridimensionais
Arrays tridimensionais são o suficiente para lidar com muitas necessidades. Possui o mesmo padrão dos exemplos anteriores, com a diferença que possui mais uma dimensão. Depois da terceira dimensão começa a ficar um pouco mais complexo. Como não tenho a intenção de atrapalhar o seu aprendizado até aqui, assim espero, deixarei os tópicos mais complexos para outro material. Por enquanto estamos indo bem.

In [ ]:
arrayTri = np.array([ [[1,2,3,4],[1,2,3,4]], [[1,2,3,4],[1,2,3,4]] ])
arrayTri

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

### Provando as dimensões
Agora que sabemos criar matrizes e vetores com o python, vamos tirar a prova das dimensões.

Para isso, basta utilizar o "ndim" do python e teremos a dimensão como resultado.

In [ ]:
#Unidimensional
arrayUni.ndim

1

In [ ]:
#Bidimensional
matrixBi.ndim

2

In [ ]:
#tridimensional
arrayTri.ndim

3

### Tamanho
Lembra que no começo aprendemos que o tamanho das matrizes são representadas por m x n?
A letra m representa as linhas e a n as colunas. Usando o "shape" podemos saber o tamanho de qualquer matriz.


In [ ]:
matrixBi.shape

(2, 3)

### Maior valor
Para saber o maior valor dentro de uma matriz podemos utilizar a função "max". Lembrando que a função não trabalha com vetores unidimensionais. Nem mesmo com os que possuem mais de um tipo de valores.


In [ ]:
arrayTri.max()

4

### Vamos para operações
Trabalhar com operações em matrizes e vetores é relativamente muito simples. Torna ainda mais fácil quando temos o python ou qualquer outra linguagem como nosso aliado. Criarei primeiramente uma matriz e realizarei algumas operações simples. Entenda que no lugar da matriz poderia ser um vetor.

In [ ]:
# Matriz A
matrixA = np.matrix([ [2,4,6,8], [1,3,5,7], [9,11,13,15], [12,14,16,18] ])
print(matrixA)

[[ 2  4  6  8]
 [ 1  3  5  7]
 [ 9 11 13 15]
 [12 14 16 18]]


#### Soma

In [ ]:
matrixA + 2

matrix([[ 4,  6,  8, 10],
        [ 3,  5,  7,  9],
        [11, 13, 15, 17],
        [14, 16, 18, 20]])

Repare que a operação é feita elemento por elemento.

#### Subtração


In [ ]:
matrixA - 1

matrix([[ 1,  3,  5,  7],
        [ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [11, 13, 15, 17]])

#### Multiplicação

In [ ]:
matrixA * 3

matrix([[ 6, 12, 18, 24],
        [ 3,  9, 15, 21],
        [27, 33, 39, 45],
        [36, 42, 48, 54]])

#### Divisão

In [ ]:
matrixA / 4

matrix([[0.5 , 1.  , 1.5 , 2.  ],
        [0.25, 0.75, 1.25, 1.75],
        [2.25, 2.75, 3.25, 3.75],
        [3.  , 3.5 , 4.  , 4.5 ]])

#### Potência

In [ ]:
matrixA ** 2

matrix([[158, 198, 238, 278],
        [134, 166, 198, 230],
        [326, 422, 518, 614],
        [398, 518, 638, 758]])

### Operações entre matrizes
Criaremos outra matriz para realizar as operações.   
Todo o resultado será armazenado em uma matriz chamada 'c'.

In [ ]:
# Matriz B
matrixB = np.matrix([ [4,1,2,7], [5,3,2,2], [7,15,3,13], [11,16,5,21] ])

In [ ]:
matrixB

matrix([[ 4,  1,  2,  7],
        [ 5,  3,  2,  2],
        [ 7, 15,  3, 13],
        [11, 16,  5, 21]])

In [ ]:
matrixA

matrix([[ 2,  4,  6,  8],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [12, 14, 16, 18]])

#### Soma

In [ ]:
matrixC = matrixA + matrixB
matrixC

matrix([[ 6,  5,  8, 15],
        [ 6,  6,  7,  9],
        [16, 26, 16, 28],
        [23, 30, 21, 39]])

Os elementos de cada matriz ou vetor são somados uns com os outros criando uma nova matriz ou vetor.

#### Subtração

In [ ]:
matrixC = matrixA - matrixB
matrixC

matrix([[-2,  3,  4,  1],
        [-4,  0,  3,  5],
        [ 2, -4, 10,  2],
        [ 1, -2, 11, -3]])

#### Multiplicação

In [ ]:
matrixC = matrixA * matrixB
matrixC

matrix([[158, 232,  70, 268],
        [131, 197,  58, 225],
        [347, 477, 154, 569],
        [428, 582, 190, 698]])

#### Divisão

In [ ]:
matrixC = matrixA / matrixB
matrixC

matrix([[0.5       , 4.        , 3.        , 1.14285714],
        [0.2       , 1.        , 2.5       , 3.5       ],
        [1.28571429, 0.73333333, 4.33333333, 1.15384615],
        [1.09090909, 0.875     , 3.2       , 0.85714286]])

### Condições lógicas
Operações lógicas trabalham com valores booleanos. Um dado booleano só pode assumir dois valores, verdadeiro(True) e falso(False). Irei disponibilizar uma tabela "verdade" para um melhor entendimento do assunto. Caso você não tenha nenhum conhecimento prévio indico que faça uma pesquisa antes. Apesar de simples é muito importante entender condições lógicas. Utilizamos comumente na matemática e na computação.   

Recomendo essa aula do curso em video com o professor Guanabara ([Operadores Lógicos e Relacionais - Curso de Algoritmos #04 - Gustavo Guanabara](https://www.youtube.com/watch?v=Ig4QZNpVZYs&list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV&index=5)).



```
        Tabela verdade
  P   |   Q   |  OR   |  AND  |
----- | ----- | ----- | ----- |
  V   |   V   |   V   |   V   |
  V   |   F   |   V   |   F   |
  F   |   V   |   V   |   F   |
  F   |   F   |   F   |   F   |
```




In [ ]:
# Array A
arrayA = np.array([[3,2,7,9,2], [7,4,3,9,1]])
arrayA

array([[3, 2, 7, 9, 2],
       [7, 4, 3, 9, 1]])

In [ ]:
# Array B
arrayB = np.array([[12, 2, 5, 9, 7],[7, 4, 3, 9, 0]])
arrayB

array([[12,  2,  5,  9,  7],
       [ 7,  4,  3,  9,  0]])

#### Igualdade

In [ ]:
# Quais elementos do Array A são iguais aos do array B?
'''
  False = Diferente
  True = Igual
'''
arrayA == arrayB

array([[False,  True, False,  True, False],
       [ True,  True,  True,  True, False]])

#### Diferença

In [ ]:
# Quais elementos do Array A são diferentes aos do array B?
'''
  False = Diferente
  True = Igual
'''
arrayA != arrayB

array([[ True, False,  True, False,  True],
       [False, False, False, False,  True]])

#### Menor Que...

In [ ]:
# Quais elementos do Array A são menores que os do array B?
'''
  False = Maior ou igual
  True = Menor
'''
arrayA < arrayB

array([[ True, False, False, False,  True],
       [False, False, False, False, False]])

#### Maior que...


In [ ]:
# Quais elementos do Array A são maiores que os do array B?
'''
  False = Menor ou igual
  True = maior
'''
arrayA > arrayB

array([[False, False,  True, False, False],
       [False, False, False, False,  True]])

Espero que você tenha aprofundado seu conhecimento sobre condições lógicas. Vamos utilizar funções com operações mais específicas nesse momento.

Vamos atribuir valores boleanos aleatórios para os arrays A e B. Cada array recebe um novo nome p e q.

In [ ]:
# Array A = Array p
arrayA = np.array([True, True, False, False])
p = arrayA
# Array B = Array Q
arrayB = np.array([True, False, True, False])
q = arrayB

In [ ]:
# Array A
p

array([ True,  True, False, False])

In [ ]:
# Array B
q

array([ True, False,  True, False])

#### OR
Essa função compara se os valores boleanos de um ou outro são true. Se for verdadeiro retorna o valor True.

In [ ]:
# Comparação 'OR' entre os valores de P e Q
np.logical_or(p,q)

array([ True,  True,  True, False])

#### AND
Os valores tanto de um array quanto de outro deve ser true. Caso seja verdadeiro ele retorna true, se for falso, false.

In [ ]:
# Comparação 'AND' entre os valores de P e Q
np.logical_and(p,q)

array([ True, False, False, False])

### Indexação de arrays
Basicamente cada elemento em um array possui um índice como referência.
Desde o índice do primeiro elemento até o índice do último elemento, seguindo sequencialmente(0, 1, 2, 3, 4...). Dessa forma podemos indexar cada elemento e usar como referência. É extremamente comum o uso desses índices como referência.

Vamos criar dois arrays para os exemplos:

In [ ]:
# Primeiro array
arrayA = np.array([12, 23, 55, 42])
# Segundo array
arrayB = np.array([32, 44, 52, 26, 19])

Cada valor de cada array possui uma estrutura de índices da seguinte forma:  
```
 0    1   2   3
[12, 23, 55, 42]

 0    1   2   3   4
[32, 44, 52, 26, 19]
```
Vamos usar os índices para printar na tela seus respectivos valores.  
Compare o código com a tabela.

In [ ]:
# Array 'A' valor '12' com o indice '0'
arrayA[0]

12

In [ ]:
# Array 'B' valor '32' com o indice '0'
arrayB[0]

32

In [ ]:
# Array 'A' valor '42' com o indice '3'
arrayA[3]

42

In [ ]:
# Array 'B' valor '19' com o indice '4'
arrayB[4]

19

Agora vamos listar todos os valores de cada array.

In [ ]:
arrayA[0:4]

array([12, 23, 55, 42])

In [ ]:
arrayB[0:5]

array([32, 44, 52, 26, 19])

Existe uma forma mais simples de usar caso você não saiba os índices iniciais e finais.

In [ ]:
arrayA[:]

array([12, 23, 55, 42])

O [ : ] sem valor nenhum é usado para dizer que você precisa de todos os elementos do índice inicial até o índice final.

Você pode escolher mostrar os valores com intervalos de x em x. Para isso, basta passar um terceiro parâmetro com o número de intervalos.

In [ ]:
arrayB[ : :2]

array([32, 52, 19])

Vamos agora pegar o último elemento.

In [ ]:
arrayB[-1]

19

Podemos também concatenar os dois arrays dentro de um novo array.

#### Dentro de apenas uma linha

In [ ]:
c = np.concatenate([arrayA,arrayB])
c

array([12, 23, 55, 42, 32, 44, 52, 26, 19])

#### Com duas ou mais linhas

In [ ]:
c = np.concatenate([[arrayA],[arrayA]])
c

array([[12, 23, 55, 42],
       [12, 23, 55, 42]])

Algo interessante  é que você pode alterar os valores de cada elemento percorrendo o array.

In [ ]:
arrayA[0:3] = 0
arrayA

array([ 0,  0,  0, 42])

Vamos aprender agora a trabalhar com indexação de arrays multidimensionais.

In [ ]:
# Listando as linhas e colunas
c[: , :]

array([[12, 23, 55, 42],
       [12, 23, 55, 42]])

In [ ]:
# Listando apenas a primeira linha
c[0]

array([12, 23, 55, 42])

In [ ]:
# Listando apenas a segunda linha
c[1]

array([12, 23, 55, 42])

In [ ]:
# Listando apenas a primeira coluna
c[: , 0]

array([12, 12])

In [ ]:
# Listando apenas a última coluna
c[: , -1]

array([42, 42])

In [ ]:
# Listando os elementos centrais
c[0:3, 1:3 ]

array([[23, 55],
       [23, 55]])

### Ordenando arrays
Podemos reorganizar o array ou matriz em ordem crescente com o sort.  
Lembrando que ele irá organizar por linha. 

In [ ]:
matrixA.sort(axis = 1)
matrixA

matrix([[ 2,  4,  6,  8],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [12, 14, 16, 18]])

### Transformando matriz em lista
Existe uma maneira simples de transformar matrizes em lista:

In [ ]:
matrixA

matrix([[ 2,  4,  6,  8],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [12, 14, 16, 18]])

In [ ]:
matrixA = matrixA.ravel()
matrixA

matrix([[ 2,  4,  6,  8,  1,  3,  5,  7,  9, 11, 13, 15, 12, 14, 16, 18]])

### Transformando lista em matriz
E listas em tabelas:

In [ ]:
matrixA = matrixA.reshape(4,4)
matrixA

matrix([[ 2,  4,  6,  8],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [12, 14, 16, 18]])

### Realizando buscas com any e all
Podemos utilizar o any e all para realizar buscas por valores dentro de uma lista ou matriz.  
Any: Usado para realizar buscas por um único valor(Retorna true quando encontrado).  
All: Para buscas por todos os valores(Retorna true quando todos os valores possuem uma propriedade específica). 


In [ ]:
# Dentro de matrixA existe um elemento com valor 14?
np.any(matrixA == 14)


True

In [ ]:
# Todos os valores de matrixA são divisíveis por 2?
np.all((matrixA % 2) == 0)

False

### Cópias
Não basta apenas referenciar, devemos realizar uma cópia para que uma variável possa realmente possuir o valor de outra variável, caso contrário, será apenas uma referência.

In [ ]:
# Criando variável a
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [ ]:
# Vamos criar uma cópia
b = a.copy()
b

array([0, 1, 2, 3])

Você deve ter percebido o quanto foi importante ter entendido a base de matrizes e arrays.   
Vamos facilitar ainda mais o processo.

### Dot product
A soma dos produtos de duas matrizes.
```
a = [2, 2, 5]
b = [2, 3, 1]
a * b = c
c = [4, 6, 5]
dot = 4 + 6 + 5 -> 15

```

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b

array([0, 1, 2, 3])

In [ ]:
np.dot(a,b)

14

### Matriz transposta
Troca das linhas de uma matriz pelas suas colunas.

In [ ]:
matrixA

matrix([[ 2,  4,  6,  8],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [12, 14, 16, 18]])

In [ ]:
np.transpose(matrixA)

matrix([[ 2,  1,  9, 12],
        [ 4,  3, 11, 14],
        [ 6,  5, 13, 16],
        [ 8,  7, 15, 18]])

### Broadcasting
É como chamamos a soma de uma matriz com a sua transposta.

In [ ]:
np.transpose(matrixA) + matrixA

matrix([[ 4,  5, 15, 20],
        [ 5,  6, 16, 21],
        [15, 16, 26, 31],
        [20, 21, 31, 36]])

### Tipagem de dados
É possível passar por parâmetro o tipo de cada array ou matriz.

In [ ]:
# Array com valores do tipo float por parâmetro
array = np.array([12, -23, 20.12, 52], dtype = 'float')
array

array([ 12.  , -23.  ,  20.12,  52.  ])

In [ ]:
# Verifica o tipo do array que deve retornar 'float'
array.dtype

dtype('float64')

In [ ]:
# Array com valores do tipo int por parâmetro
array = np.array([12, -23, 20.12, 52], dtype = 'int')
array

array([ 12, -23,  20,  52])

In [ ]:
# Verifica o tipo do array que deve retornar 'int'
array.dtype

dtype('int64')

### O método arange
Usamos o arange para criar arrays com auto incremento. Passando por parâmetro os devidos valores, temos como resultado um array construído por estruturas de repetição.

Array com 10 valores de 0 a 9:

In [ ]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Array de 0 a 50 com intervalos a cada 5:

In [ ]:
array = np.arange(0, 51, 5)
array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

### Estrutura de dados com linspace
Responsável por distribuir os valores de um array em um determinado intervalo.  

Exemplo: Temos o intervalo entre 0 e 10, precisamos de 20 valores entre esse intervalo. O linspace realizará a distribuição regular entre cada elemento entre o intervalo.

De 0 a 10 com o total de 20 valores:

In [ ]:
array = np.linspace(0, 10, 20)
array

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### Estruturando arrays
É possível criar arrays com valores únicos de um determinado tamanho.   
Muito usado em modelos de machine learn e IA.

#### Zeros

In [ ]:
# Array com valores 0, com 4 linhas e  4 colunas
array = np.zeros((4,4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Ones

In [ ]:
# Array com valores 1, com 4 linhas e 3 colunas
array = np.ones((4,3))
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Eye
Podemos utilizar o 'eye' para criar matrizes com diagonais do tipo identidade.

In [ ]:
# Array de tamanho L X C do tipo identity
array = np.eye(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Diag
Podemos passar os valores da diagonal.

O tamanho do array é proporcional a quantidade de itens na diagonal.

In [ ]:
array = np.diag((6,7,8,9))
array

array([[6, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

#### Tile
Você passa os valores de uma matriz e poderá multiplicá-los dentro da mesma linha.

In [ ]:
array = np.tile(np.array([[0,1],[2,3], [4,5], [6,7]]), (2))
array

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])

In [ ]:
array = np.tile(np.array([[0,1],[2,3], [4,5], [6,7]]), (2,3))
array

array([[0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3],
       [4, 5, 4, 5, 4, 5],
       [6, 7, 6, 7, 6, 7],
       [0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3],
       [4, 5, 4, 5, 4, 5],
       [6, 7, 6, 7, 6, 7]])

## Conclusão
Apesar de muito importante, álgebra linear é fácil e simples. É verídico que ela esta presente em diversos setores da tecnologia e matemática. Na computação é muito comum o uso de matrizes e vetores. A tela do seu celular ou computador é basicamente formada por matrizes. Outro exemplo que posso apresentar é a inteligência artificial e/ou machine learning. Por isso, torna-se quase que indispensável o entendimento do mesmo.

**Fim!**

**Por enquanto... :)**